var listOfIndustries = [
    
    "Government Operations and Politics",
    "International Affairs",
    "Commerce",
    "Environmental Protection",
    "Health",
    "Science, Technology, Communications",
    "Immigration",
    "Education",
    "Native Americans",
    "Crime and Law Enforcement",
    "Public Lands and Natural Resources",
    "Armed Forces and National Security",
    "Congress",
    "Finance and Financial Sector",
    "Agriculture and Food",
    "Transportation and Public Works",
    "Taxation",
    "Agriculture and food",
    "Water resources development",
    "Social welfare",
    "Law",
    "Income tax",
    "Transportation and public works",
    "Environmental protection",
    "Copyright",
    "Government trust funds",
    "Foreign trade and international finance",
    "International affairs",
    "Families",
    "House of Representatives",
    "Armed forces and national security",
    "Gambling",
    "Senate",
    "Congressional tributes",
    "Special months",
    "Intergovernmental relations",
    "Money",
    "Economics and public finance",
    "Elementary and secondary education",
    "Crime and law enforcement",
    "Commemorations",
    "Drug abuse",
    "Government operations and politics",
    "Public lands and natural resources",
    "Housing and community development",
    "Emergency management",
    "Private legislation",
    "Civil rights and liberties, minority issues",
    "Labor and employment",
    "Finance and financial sector",
    "Science, technology, communications",
    "Energy",
    "Economics and Public Finance",
    "Emergency Management",
    "Animals",
    "Wildlife refuges",
    "Wilderness areas",
    "Appropriations",
    "Securities",
    "Recreation",
    "Nuclear energy",
    "Historic sites",
    "Federal employees",
    "Travel",
    "Disabled",
    "Higher education",
    "Minorities",
    "Marine and coastal resources, fisheries",
    "Social sciences and history",
    "Water Resources Development",
    "Government",
    "Arts, Culture, Religion",
    "Labor and Employment"
]

module.exports = listOfIndustries;